### ISSUE TITLE
issue with scalar strings

### ISSUE THREAD

**Issue by simonrglenn** [learn-co-curriculum/programming-univbasics-data-types#3]
if strings are on a scale from A-z running through both upper and lower case, it may be more instructive to start with "AAA" as your example to then reach "AAz" and then carry the letter to "ABA". Capitalization matters. 
Also wouldn't from "aaa" to "aab" be "going DOWN one" on the list? (Or UP in value?)

**Comment by sgharms** [comment]
Interesting point. We'll integrate this.
