### ISSUE TITLE
Spelling error in this lesson

### ISSUE THREAD

**Issue by LordLeviticus** [learn-co-curriculum/programming-univbasics-data-types#4]
In this lesson there is a sentence written as follows:

A baby spends the fist 3-5 years of their life running assignment expressions learning about "dogs," "boats," and "trains." They're adding "bare words" to their vocabulary that point to things.

It should say a baby spends the "FIRST" 3 - 5 years. 

This isn't a huge issue, but could more than likely be easily fixed and makes the information more professional. Thanks

**Comment by maxwellbenton** [comment]
Hi @LordLeviticus,

Thank you for spotting this and providing feedback. This typo has been fixed.
